version: "3.8"

services:
  php-apache-environment:
    container_name: php-apache-looper
    build:
      context: ./docker/
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/public
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql
    restart: always
    env_file:
      - ./docker/db.env
    ports:
      - "9906:3306"
